spring.application.name=Online_Shop
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=aria2015
spring.datasource.url=jdbc:mysql://localhost:3306/medical_clinic?createDatabaseIfNotExist=true
server.error.include-message=always
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin
